version: '3.4'

services:
  pl:
    image: ${DOCKER_REGISTRY-}pl
    build:
      context: .
      dockerfile: PL/Dockerfile
    depends_on:
      - sqlserverService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"

  sqlserverService:
    image: mcr.microsoft.com/mssql/server:latest
